Accept a 'keyId' argument to indicate the KMS key for new encryption
rotaready/node-credstash pull request #2
Opened 2017-03-29 20:10 UTC by glyph

It would be useful to be able to have different entities use different keys for encryption for different permission levels.  (As I understand it, decryption should automatically select the appropriate key.)

2017-03-30 15:08 UTC, Rhysjc requested changes
Great idea, if we can just make these changes I'm happy to merge it in

2017-03-30 15:08 UTC, Rhysjc commented on lib/KMS.js
> +    constructor(region, keyId) {
Would be great if we could use an ES6 default param here instead of the check below

2017-03-30 22:48 UTC, glyph commented
Should be fixed; let me know if there's anything else!

2017-04-03 17:19 UTC, glyph commented
I missed that other location for a default param, hopefully that's it though?

2017-04-11 15:48 UTC, Rhysjc approved these changes

2017-04-11 15:49 UTC, Rhysjc commented
Looks great! Merging in 👍

2017-04-11 15:49 UTC, merged

2017-04-17 17:35 UTC, glyph commented
Thanks; appreciated!